### ISSUE TITLE
[Egg Request]: <Vrising> Rcon tool to shedule server announcements like "Server restart in 10min"

### ISSUE THREAD

**Issue by TraeF1337** [pelican-eggs/tooling#1]
### Does this expand an already existing service

Yes

### Link to a game or software

https://github.com/StunlockStudios/vrising-dedicated-server-instructions

### Links for the download

https://github.com/gorcon/rcon-cli

### Links for the install docs

https://github.com/StunlockStudios/vrising-dedicated-server-instructions/blob/master/1.0.x/INSTRUCTIONS.md#rcon-1

**Comment by QuintenQVD0** [comment]
This isn't feasible. An egg can't execute tasks every 10 minutes, and adding another just to send an RCON message isn't practical. As long as our schedule can't run commands, this solution won't really work. sorry!
